### ISSUE TITLE
I got an error when try it with my ollama gemma2:2b model

### ISSUE THREAD

**Issue by Inklare** [jakobdylanc/llmcord.py#56]
2024-08-30 16:07:18,677 INFO: HTTP Request: POST http://127.0.0.1:11434/chat/completions "HTTP/1.1 404 Not Found"
2024-08-30 16:07:18,678 ERROR: Error while generating response
Traceback (most recent call last):
  File "D:\Microsoft VS code projects\llmcord.py-main\llmcord.py", line 188, in on_message
    async for curr_chunk in await openai_client.chat.completions.create(**kwargs):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mokch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\resources\chat\completions.py", line 1339, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\mokch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\_base_client.py", line 1816, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mokch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\_base_client.py", line 1510, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mokch\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\openai\_base_client.py", line 1611, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: 404 page not found

**Comment by jakobdylanc** [comment]
It looks like you have the ollama base_url set incorrectly. It should be:

"http://localhost:11434/v1"

Make sure you have that "/v1" at the end.

**Comment by Inklare** [comment]
> It looks like you have the ollama base_url set incorrectly. It should be:
> 
> "http://localhost:11434/v1"
> 
> Make sure you have that "/v1" at the end.

OOH, THANK YOU VERY MUCH
