### ISSUE TITLE
Groq broken?

### ISSUE THREAD

**Issue by RizkyM2999** [jakobdylanc/llmcord.py#62]
Groq seems broken

`2024-10-28 13:28:27,141 INFO: HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
2024-10-28 13:28:27,142 ERROR: Error while generating response
Traceback (most recent call last):
  File "/home/container/llmcord.py", line 201, in on_message
    async for curr_chunk in await openai_client.chat.completions.create(**kwargs):
  File "/home/container/.local/lib/python3.11/site-packages/openai/_streaming.py", line 147, in __aiter__
    async for item in self._iterator:
  File "/home/container/.local/lib/python3.11/site-packages/openai/_streaming.py", line 193, in __stream__
    raise APIError(
openai.APIError: Service Unavailable`

**Comment by RizkyM2999** [comment]
> Just tested and it works for me. Did you test with other models from Groq? Or with other providers?
> 
> ```
> 2024-10-28 13:31:29,418 INFO: HTTP Request: POST https://api.groq.com/openai/v1/chat/completions "HTTP/1.1 200 OK"
> ```

No im just use Groq with Mixtral model when i tested log says 200 OK but not replying in discord

**Comment by jakobdylanc** [comment]
Have you tested again recently?
