### ISSUE TITLE
peer closed connection without sending complete message (Yes, again.)

### ISSUE THREAD

**Issue by T9es** [jakobdylanc/llmcord.py#64]
Are we positive that oobabooga is working correctly? I've seen some issues here, even seen test scripts for the API, but even those test scripts are giving me this exact error.

```
2024-11-01 02:26:50,926 INFO: HTTP Request: POST http://192.168.1.13:5000/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-01 02:26:50,963 ERROR: Error while generating response
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\httpx\_transports\default.py", line 72, in map_httpcore_exceptions
    yield
  File "C:\Python311\Lib\site-packages\httpx\_transports\default.py", line 257, in __aiter__
    async for part in self._httpcore_stream:
  File "C:\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 367, in __aiter__
    raise exc from None
  File "C:\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 363, in __aiter__
    async for part in self._stream:
  File "C:\Python311\Lib\site-packages\httpcore\_async\http11.py", line 349, in __aiter__
    raise exc
  File "C:\Python311\Lib\site-packages\httpcore\_async\http11.py", line 341, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
  File "C:\Python311\Lib\site-packages\httpcore\_async\http11.py", line 210, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\httpcore\_async\http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "C:\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\server\Desktop\LLMcord\llmcord.py", line 201, in on_message
    async for curr_chunk in await openai_client.chat.completions.create(**kwargs):
  File "C:\Python311\Lib\site-packages\openai\_streaming.py", line 147, in __aiter__
    async for item in self._iterator:
  File "C:\Python311\Lib\site-packages\openai\_streaming.py", line 160, in __stream__
    async for sse in iterator:
  File "C:\Python311\Lib\site-packages\openai\_streaming.py", line 151, in _iter_events
    async for sse in self._decoder.aiter_bytes(self.response.aiter_bytes()):
  File "C:\Python311\Lib\site-packages\openai\_streaming.py", line 302, in aiter_bytes
    async for chunk in self._aiter_chunks(iterator):
  File "C:\Python311\Lib\site-packages\openai\_streaming.py", line 313, in _aiter_chunks
    async for chunk in iterator:
  File "C:\Python311\Lib\site-packages\httpx\_models.py", line 931, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
  File "C:\Python311\Lib\site-packages\httpx\_models.py", line 989, in aiter_raw
    async for raw_stream_bytes in self.stream:
  File "C:\Python311\Lib\site-packages\httpx\_client.py", line 150, in __aiter__
    async for chunk in self._stream:
  File "C:\Python311\Lib\site-packages\httpx\_transports\default.py", line 256, in __aiter__
    with map_httpcore_exceptions():
  File "C:\Python311\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python311\Lib\site-packages\httpx\_transports\default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
```

I've updated everything. I've checked flags, I've added flags to oobabooga itself in the CMD FLAGS file, nothing is working. This is running inside docker. 

I've tried running the DarkIdol-Llama-3.1-8B-Instruct-1.2-Uncensored-Q4_K_S-imat.gguf model first, didn't work. Then I switched over to Llama-3.2-1B-Instruct-Q4_K_S.gguf, didn't work. 

Edit: Tried out llama-2-7b-chat.Q4_K_M.gguf as a last resort, that gave the same error.

**Comment by jakobdylanc** [comment]
Sorry you struggled for so long with this.

"max_tokens" is a standard OpenAI API parameter that llmcord.py simply passes to oobabooga. It's not a llmcord.py specific thing if that's what you're thinking. 

The whole point of "extra_api_parameters" in llmcord.py's config is to let you pass any API parameters you want. I include "max_tokens" and "temperature" because those are pretty standard, but you can change them, remove them and add more as you please. 

Same with the system prompt. If you're having issues with large system prompts then that would be a oobabooga issue. Or maybe a weakness of whatever LLM you're using.

Hope that helps.

**Comment by jakobdylanc** [comment]
oobabooga has some additional custom API parameters that you have to refer to its documentation for. But for standard OpenAI API parameters (which oobabooga supports, since it is OpenAI compatible) you can refer to here for their definitions: https://platform.openai.com/docs/api-reference/chat/create
